name: Daily TradingView Update

on:
  schedule:
    - cron: "5 20 * * 1-5"  # Runs at 4:05 PM ET (20:05 UTC) on weekdays
  workflow_dispatch:  # Enables manual trigger from GitHub Actions UI
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: latest_release
        run: echo "tag=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV

      - name: Checkout Latest Release
        uses: actions/checkout@v3
        with:
          ref: ${{ env.tag }}  # Pulls the latest release

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run TradingView Scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
